#!/bin/sh
_LBUDEFDIR=$HOME/.locabinup
[ -z "$XDG_DATA_HOME" ] || _LBUDEFDIR="$XDG_DATA_HOME/locabinup"
export LOCABINUPDIR="${LOCABINUPDIR:-$_LBUDEFDIR}"
set -e
case $1 in
	update|"")
		echo "Let's update"
		for scr in $(ls $LOCABINUPDIR/world);do
			echo checking $scr
			sh $LOCABINUPDIR/world/$scr
		done
		;;
	list)
		for w in $(ls $LOCABINUPDIR/world)
		do
			echo "$w version "`cat $LOCABINUPDIR/world/.$w`
		done
		;;
	add)
		[ -z "$2" ] && echo "empty string" && exit
		cp $LOCABINUPDIR/universe/$2 $LOCABINUPDIR/world
		sh $LOCABINUPDIR/world/$2
		;;
	rm)
		[ -z "$2" ] && echo "empty string" && exit
		rm $LOCABINUPDIR/world/$2 $LOCABINUPDIR/world/.$2
		;;
	fd)
		ls -1 $LOCABINUPDIR/universe | grep -i "$2"
		;;
	*)
		echo "usefull help message 88w88"
		;;
esac
