#!/bin/sh
set -eu
export _VERS=$(curl -s https://api.github.com/repos/sindresorhus/caprine/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'| cut -c2-)
if [ "$_VERS" = "$(cat $LOCABINUPDIR/world/.caprine)" ]
then
	echo "Already up to date"
	exit
fi
echo "updating caprine"
cd ~/.local/bin/
curl -LJO "https://github.com/sindresorhus/caprine/releases/download/v$_VERS/Caprine-$_VERS.AppImage"
mv -vf Caprine-$_VERS.AppImage caprine.AppImage
chmod +x caprine.AppImage
echo $_VERS > $LOCABINUPDIR/world/.caprine
